apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP     
  selector:
    app: backend      
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend     
spec:
  containers:
  - name: backend
    image: springcommunity/spring-petclinic-rest
    ports:
    - containerPort: 9966